[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lab_llm"  
version = "1.0.1" 
description = "API logic to call different LLMs using LiteLLM"
authors = [{name = "Jean Feng", email = "jean.feng@ucsf.edu"}]  
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "dotenv>=0.9.9",
    "duckdb>=0.7.0",
    "litellm>=1.83.1",
    "openai>=1.66.5",
    "tiktoken>=0.9.0"
]
